### ISSUE TITLE
How to enable SSL?

### ISSUE THREAD

**Issue by tahir-gvs** [joomla/docker-joomla#18]
I see `/etc/apache2/sites-available/default-ssl.conf` is included in the container.  What is the recommended way to enable ssl without create a new image `FROM docker-joomla`. 

Should we just copy the `default-ssl.conf`, modify it and mount it on '/etc/apache2/sites-enabled' along with mount volume for the actual ssl certificates, or do we need to some additional step too  ?

**Comment by tahir-gvs** [comment]
Apparently, Apache SSL module is not enabled in this or base Dockerfile so it won't be possible to enable SSL without creating a custom image from docker-joomla

**Comment by mbabker** [comment]
Your best option is probably going to be to extend this image to add it in.  Since it isn't something that could be set up automatically with this base image, I think it'd be better to leave it to users needing SSL support to build an image with it (which would probably contain a default functional SSL configuration and certificates depending on use case).
