### ISSUE TITLE
Change JOOMLA_VERSION and JOOMLA_SHA1 from ENV to ARG

### ISSUE THREAD

**Issue by dukeofgaming** [joomla/docker-joomla#22]
It would be nice to allow overriding these variables at build time in order to be able to install later versions not yet distributed officially.

**Comment by mbabker** [comment]
Based on the [repeatability guideline](https://github.com/docker-library/official-images#repeatability), I'm going to close this out as a won't fix.

Generally I'm good about updating the image on release day, but as of late I've had some hectic schedules that made this a bit more complicated than need be.

If there ever is a time where this falls out of sync with the main releases for more than a day or two, updating the images is as simple as running the [update.php](https://github.com/joomla/docker-joomla/blob/master/update.php) script here in the repo and submitting a PR.  Then I can send the needed PR upstream to the `official-images` library to get that updated.

I've also got an [open task](https://github.com/joomla/joomla-websites/issues/717) to just automate this whole thing through our Jenkins CI server so part of the release pipeline would be to update this library and send the update PR upstream.  It's just been low priority since this is about 90 seconds of work for me to update everything every month or two.
