### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [joomla/docker-joomla#64]
Hi,

The Joomla docker package is building and running fine at my end for ARM64v8 architecture.

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by mbabker** [comment]
Architecture support is in the image now.  @J0WI I thought after adding this repo to their CI everything would kind of update itself, the files here have been updated but the [image file](https://github.com/docker-library/official-images/blob/master/library/joomla) hasn't yet (and I still can't run the `generate-stackbrew-library.sh` script on any of my systems because of that `./generate-stackbrew-library.sh: line 116: parentRepoToArches[$variantParent]: unbound variable` message.

**Comment by odidev** [comment]
@mbabker : Is there anything, which can be done at my end for this issue?

**Comment by lag-linaro** [comment]
@mbabker once the image file has been updated with the Architecture: tag, the Docker Hub builder will automatically produce and publish `docker pull`able images for you.

**Comment by odidev** [comment]
@mbabker : if you agree then I can push the change with architecture tag too.
But I wonder that whether I should push the same for all tags or just tested ```tag: latest, 3, 3.8 - php7.1/apache ```

**Comment by lag-linaro** [comment]
@odidev I have only been enabling tags that have been tested.

Enabling untested tags is a dangerous game. :smile:

**Comment by lag-linaro** [comment]
I now see Joomla has been enabled for ARM64v8.

It's in the queue to be built in Docker's builders. :+1:

**Comment by odidev** [comment]
```docker pull joomla``` is still not working for arm64v8

**Comment by mbabker** [comment]
As was pointed out, it was still queued somewhere it seems.  The official [hub page](https://hub.docker.com/_/joomla/) says the image was updated roughly 15 minutes before this comment, which aligns with https://github.com/docker-library/repo-info/tree/master/repos/joomla.

**Comment by odidev** [comment]
Thanks @mbabker  :smiley:

**Comment by lag-linaro** [comment]
Right.  I just re-checked and the build succeeded.

It is now possible to `docker pull joomla` on ARM64v8 platforms.  \o/

Thank you for your efforts.  I believe this issue can now be closed.
