### ISSUE TITLE
How can I get logs when developing joomla plugins

### ISSUE THREAD

**Issue by Skeeve** [joomla/docker-joomla#67]
Bear with me, I'm new to docker and joomla.

I'm trying to create a joomla plugin and test this with your docker-joomla image.

Unfortunately I can only see http requests being logged when running

    docker logs --details -f some-joomla

I tried to log with

    JLog::add('my error message', JLog::ERROR);

**Comment by mbabker** [comment]
First, you need to ensure you pass a category to the `JLog::add()` call, otherwise the message might not be logged at all if there isn't a logger enabled to process all categories (which would include no category).  So `JLog::add('message', JLog::ERROR, 'category');`.

Second, you need to make sure a logger is actually enabled.  If you turn on the "System - Debug" plugin, there's an option in there to make sure "almost everything" is logged.  Otherwise, in the code you need to manually register a logger with `JLog::addLogger()`.

Third, you'll get the log files out of the Joomla install.  By default they're stored in the `administrator/logs` directory.  Using the `docker` CLI won't let you get these logs, Joomla doesn't have an integration to write logs direct to Docker.

**Comment by Skeeve** [comment]
Thanks @mbabker 

> Third, you'll get the log files out of the Joomla install. By default they're stored in the administrator/logs directory.

Okay… But how would I get that? I have no clue how to access docker's filesystem from my host system. As I said: New to docker :(
